# Generated by Django 3.2.6 on 2021-12-03 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('data_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Xenon.data')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='static/images/articles')),
                ('text', models.TextField()),
            ],
            bases=('Xenon.data',),
        ),
    ]
