# Generated by Django 3.2.6 on 2021-12-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Xenon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='short_title',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
