# Generated by Django 3.2.6 on 2021-12-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Xenon', '0002_article_short_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_title', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='static/images/articles')),
                ('text', models.TextField()),
            ],
        ),
    ]
